name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: |
        npm install -g pnpm

    - name: Install dependencies
      run: |
        pnpm install

    - name: Run build script
      run: |
        pnpm run build -- ${{ env.RELEASE_VERSION }}

    - name: Prepare release assets
      run: |
        mkdir LGF_Loading
        cp -r dist LGF_Loading/
        cp fxmanifest.lua LGF_Loading/
        cp LICENSE LGF_Loading/
        cp README.md LGF_Loading/

    - name: Bundle files
      run: |
        mkdir -p ./temp/LGF_Loading
        cp ./{LICENSE,README.md,fxmanifest.lua} ./temp/LGF_Loading
        cp -r ./{imports,resource,locales} ./temp/ox_lib
        cp -r ./dist ./temp/LGF_Loading/dist/
        cd ./temp && zip -r ../LGF_Loading.zip ./LGF_Loading

    - name: Create Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      id: auto_release
      with:
        repo_token: '${{ secrets.TOKEN }}'
        title: ${{ env.RELEASE_VERSION }}
        prerelease: false
        files: ox_lib.zip

      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
